version: '3.9'

services:
  frontend:
    build:
      context: ui/
      dockerfile: Dockerfile
    volumes:
      - ./ui:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_ENDPOINT=http://backend:8000
    depends_on:
      - backend

  backend:
    build:
      context: api/
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    env_file:
      - api/.env
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
